language: python
sudo: false
dist: bionic  # 18.04
python:
  - 2.7
  - 3.7
  - pypy3
if: (type = push AND branch IN (master)) OR (type = pull_request)
matrix:
  finish_fast: true
  allow_failures:
  - python: pypy3
cache:
  - pip
install:
  - python -m pip install --upgrade poetry
  - poetry install
script: poetry run py.test --cov=cihai_cli
after_success:
  - bash <(curl -s https://codecov.io/bash)
