__title__ = 'cihai-cli'
__package_name__ = 'cihai_cli'
__version__ = '0.4.0'
__description__ = 'Command line frontend for the cihai CJK language library'
__author__ = 'Tony Narlock'
__email__ = 'tony@git-pull.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2017-2018 cihai software foundation'
